* ReaderWriter

** ReaderWriterC1stringId
Process "writer" sends continuously "msg" to process "reader" which
receives it into current_message. 
- uses FIFO
- compiles
- NOT parsed by TLA (because of strings as identifiers?) Dostonbek Update: FIXED NOT IT PARSES CORRECTLY.

** ReaderWriterC1  
Same as ReaderWriterC1stringId but using constant Ids
- uses FIFO
- compiles
- NOT parsed by TLA (because of FIFO translation --> @). Dostonbek Update: FIXED NOT IT PARSES CORRECTLY.

** ReaderWriterC1array  
Same as ReaderWriterC1 but using an array of FIFOs
- uses FIFO arrays
- compiles (NOT correctly)
- parsed by TLA (but incorrect specification)

** ReaderWriterC2stringId
Same as ReaderWriterC1 but using channels
- uses CHANNEL
- compiles
- NOT parsed by TLA (because of strings as identifiers?) Dostonbek Update: the problem seems to be with SubProcSet definition? TLA+ toolbox raises error on this line

** ReaderWriterC2
Same as ReaderWriterC2stringId but using constant Ids
- uses CHANNEL
- compiles
- parsed by TLA

** SequentialClearP
- uses an unordered channel without dimensions
- compiles
- parsed by TLA
