------ MODULE AST -------
EXTENDS TLC
fairness == ""
 
ast == 
[type     |-> "uniprocess", 
 name  |-> "Dummy", 
 decls  |-> <<[var |-> "ar", eqOrIn |-> "\\in", val |-> << "[", "1", "..", "N", "->", "0", "..", "2", "]" >>], 
              [var |-> "v", eqOrIn |-> "\\in", val |-> << "[", "(", "Nodes", "\\cup", "{", "Id", "}", ")", "\\X", "Nodes", "->", "{", "}", "]" >>], 
              [var |-> "x", eqOrIn |-> "=", val |-> << "1" >>], 
              [var |-> "i", eqOrIn |-> "=", val |-> << "1" >>], 
              [var |-> "chan", eqOrIn |-> "=", val |-> << "{", "}" >>, dim |-> []], 
              [var |-> "chan1", eqOrIn |-> "=", val |-> << "{", "}" >>, dim |-> [ Nodes \cup { Id }]], 
              [var |-> "chan2", eqOrIn |-> "=", val |-> << "{", "}" >>, dim |-> [ Nodes,  Nodes]], 
              [var |-> "fif", eqOrIn |-> "=", val |-> << "<<", ">>" >>, dim |-> []], 
              [var |-> "fif1", eqOrIn |-> "=", val |-> << "<<", ">>" >>, dim |-> [ Nodes]], 
              [var |-> "fif2", eqOrIn |-> "=", val |-> << "<<", ">>" >>, dim |-> [ Nodes,  Nodes]]>>,
 defs   |-> <<  >>,
 prcds  |-> <<>>,
 body  |-> <<[label |-> "S",
              stmts |-> <<[type |-> "assignment",
                           ass  |-> <<[lhs |-> [var |-> "x", sub |-> <<  >>],
                                       rhs |-> << "ar", "[", "1", "]" >>]>>]>>], 
             [label |-> "SC",
              stmts |-> <<[type |-> "assignment",
                           ass  |-> <<[lhs |-> [var |-> "chan", sub |-> <<  >>],
                                       rhs |-> << "chan", " \cup ", "{", "x", "}" >>]>>], 
                          [type |-> "assignment",
                           ass  |-> <<[lhs |-> [var |-> "chan1", sub |-> << "[", "1", "]" >>],
                                       rhs |-> << "@", " \cup ", "{", "x", "}" >>]>>], 
                          [type |-> "assignment",
                           ass  |-> <<[lhs |-> [var |-> "chan2", sub |-> << "[", "2", ",", "1", "]" >>],
                                       rhs |-> << "@", " \cup ", "{", "x", "}" >>]>>]>>], 
             [label |-> "SF",
              stmts |-> <<[type |-> "assignment",
                           ass  |-> <<[lhs |-> [var |-> "fif", sub |-> <<  >>],
                                       rhs |-> << " Append(fif, ", "x", ")" >>]>>], 
                          [type |-> "assignment",
                           ass  |-> <<[lhs |-> [var |-> "fif1", sub |-> << "[", "1", "]" >>],
                                       rhs |-> << " Append(@, ", "x", ")" >>]>>], 
                          [type |-> "assignment",
                           ass  |-> <<[lhs |-> [var |-> "fif2", sub |-> << "[", "2", ",", "1", "]" >>],
                                       rhs |-> << " Append(@, ", "x", ")" >>]>>]>>], 
             [label |-> "Rc",
              stmts |-> <<[type   |-> "with", 
                           var    |-> "_c1613",
                           eqOrIn |-> "\\in",
                           exp    |-> << "chan" >>,
                           do     |-> <<[type |-> "assignment",
                                         ass  |-> <<[lhs |-> [var |-> "i", sub |-> <<  >>],
                                                     rhs |-> << "_c1613" >>], 
                                                    [lhs |-> [var |-> "chan", sub |-> <<  >>],
                                                     rhs |-> << "chan", " \ ", "{", "_c1613", "}" >>]>>]>>]>>], 
             [label |-> "Rf",
              stmts |-> <<[type |-> "when", 
                           exp |-> << "Len(", "fif", ") > 0 " >>], 
                          [type |-> "assignment",
                           ass  |-> <<[lhs |-> [var |-> "x", sub |-> <<  >>],
                                       rhs |-> << "Head(", "fif", ")" >>]>>], 
                          [type |-> "assignment",
                           ass  |-> <<[lhs |-> [var |-> "fif", sub |-> <<  >>],
                                       rhs |-> << " Tail(fif) " >>]>>]>>], 
             [label |-> "R1c",
              stmts |-> <<[type   |-> "with", 
                           var    |-> "_c1619",
                           eqOrIn |-> "\\in",
                           exp    |-> << "chan1", "[", "1", "]" >>,
                           do     |-> <<[type |-> "assignment",
                                         ass  |-> <<[lhs |-> [var |-> "i", sub |-> <<  >>],
                                                     rhs |-> << "_c1619" >>], 
                                                    [lhs |-> [var |-> "chan1", sub |-> << "[", "1", "]" >>],
                                                     rhs |-> << "@", " \ ", "{", "_c1619", "}" >>]>>]>>]>>], 
             [label |-> "R1f",
              stmts |-> <<[type |-> "when", 
                           exp |-> << "Len(", "fif1", "[", "1", "]", ") > 0 " >>], 
                          [type |-> "assignment",
                           ass  |-> <<[lhs |-> [var |-> "x", sub |-> <<  >>],
                                       rhs |-> << "Head(", "fif1", "[", "1", "]", ")" >>]>>], 
                          [type |-> "assignment",
                           ass  |-> <<[lhs |-> [var |-> "fif1", sub |-> << "[", "1", "]" >>],
                                       rhs |-> << " Tail(@) " >>]>>]>>], 
             [label |-> "R2c",
              stmts |-> <<[type   |-> "with", 
                           var    |-> "_c1643",
                           eqOrIn |-> "\\in",
                           exp    |-> << "chan2", "[", "2", ",", "1", "]" >>,
                           do     |-> <<[type |-> "assignment",
                                         ass  |-> <<[lhs |-> [var |-> "i", sub |-> <<  >>],
                                                     rhs |-> << "_c1643" >>], 
                                                    [lhs |-> [var |-> "chan2", sub |-> << "[", "2", ",", "1", "]" >>],
                                                     rhs |-> << "@", " \ ", "{", "_c1643", "}" >>]>>]>>]>>], 
             [label |-> "R2f",
              stmts |-> <<[type |-> "when", 
                           exp |-> << "Len(", "fif2", "[", "2", ",", "1", "]", ") > 0 " >>], 
                          [type |-> "assignment",
                           ass  |-> <<[lhs |-> [var |-> "x", sub |-> <<  >>],
                                       rhs |-> << "Head(", "fif2", "[", "2", ",", "1", "]", ")" >>]>>], 
                          [type |-> "assignment",
                           ass  |-> <<[lhs |-> [var |-> "fif2", sub |-> << "[", "2", ",", "1", "]" >>],
                                       rhs |-> << " Tail(@) " >>]>>]>>], 
             [label |-> "F",
              stmts |-> <<[type |-> "assignment",
                           ass  |-> <<[lhs |-> [var |-> "i", sub |-> <<  >>],
                                       rhs |-> << "i", "+", "1" >>]>>]>>]>>]
==========================
